export class AppUsers {
    Id:string;
    UserName: string;
    FirstName: string;
    LastName: string;
    Avatar:string;
    Email: string;
    Gender: string;
    Password: string;
    ConfirmPassword: string;
    BirthDay: Date;
    DateCreated: Date;
    DateModified: Date;
    DateVerified: Date;
    VerificationShortToken: string;
    ResetToken: string;
    DateResetTokenExpired: Date;
    AcceptTerms:boolean;
    Descriptions:string;
    Address:string;
    PhoneNumber:string;
    Works:string;
    Location: Float32Array;
    AcademicLevel:string;
    AddressAcademic:string;
    DescriptionAcademic:string;
    StudyingAt:string;
    FromDate:Date;
    ToDate:Date;
    OTP: string;
    Hobby:string;
    Language:string;
    Background:string;
    FollowMe:boolean;
    ViewTimeLine:boolean;
    ViewListFriend:boolean;
    RequestFriend:boolean;
    Active:boolean;
    NamePayment:string;
    Image:string;
}
